#!/bin/sh
# chkconfig:35 90 3
# description: grafana server manage.


appPort=3000
isWhliePid=/var/run/grafanaWhile.pid
runPaths=/home/grafana


function status(){
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
	if [ "$myPid" != "" ]; then
		echo "Started Grafana. pid = $myPid"
	else
		echo "Stopped Grafana."
	fi
}

function start(){
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
	if [ ! -z "$myPid" ]; then
		echo "Grafana进程存在，3s后重试，请稍候..."
		sleep 3
		mypid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
		if [ ! -z "$myPid" ]; then
			echo "忽略启动命令：Grafana正在运行"
			exit 1
		fi
	fi
	echo "Starting grafana..."
	su - fusecdn -c "nohup /home/grafana/bin/grafana-server --config=/home/grafana/conf/defaults.ini > /dev/null 2>&1 &"
	printf "Waiting for Grafana..."
	while true;
	do
		lsof -i:$appPort|grep LISTEN > /dev/null 2>&1
        	if [[ $? == 0 ]] ; then break; fi;
                myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
                if [ -z "$myPid" ]; then
                    echo -e "\nFailed to start Grafana."
                    exit 1
                fi
        	printf ".";
                sleep 1;
        done
	echo
    	myPid=`lsof -i:$appPort|grep LISTEN|awk '{print $2}'`
	echo "running: PID:$myPid"
}

function stop(){
   	echo "Stopping grafana..."
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
   	if [ "$myPid" != "" ]; then
                echo 0 > $isWhliePid
                kill $myPid
        fi
	printf "Waiting for Grafana..."
        while true;
	do
  		myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
		if [ "$myPid" = "" ] ; then break; fi;
  		printf ".";
  		sleep 1;
	done
	echo
}

case "$1" in
   start)
    start
    status
   ;;
   stop)
    stop
    status
   ;;
   restart)
        $0 stop
        $0 start
   ;;
   status)
   	status
   ;;
   *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit $?
   ;;
esac
