#!/bin/sh
# chkconfig:35 90 3
# description: linuxExporter server manage.



appPort=9201
isWhliePid=/var/run/linuxExporterWhile.pid
runPaths=/home/node


function status(){
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
	if [ "$myPid" != "" ]; then
		echo "Started LinuxExporter. pid = $myPid"
	else
		echo "Stopped LinuxExporter."
	fi
}

function start(){
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
	if [ ! -z "$myPid" ]; then
		echo "LinuxExporter进程存在，3s后重试，请稍候..."
		sleep 3
		mypid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
		if [ ! -z "$myPid" ]; then
			echo "忽略启动命令：LinuxExporter正在运行"
			exit 1
		fi
	fi
	echo "Starting LinuxExporter..."
	su - fusecdn -c "nohup /home/node/node_exporter --web.listen-address=:$appPort > /dev/null 2>&1 &"
	printf "Waiting for LinuxExporter..."
	while true;
	do
		lsof -i:$appPort|grep LISTEN > /dev/null 2>&1
        	if [[ $? == 0 ]] ; then break; fi;
                myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
                if [ -z "$myPid" ]; then
                    echo -e "\nFailed to start LinuxExporter."
                    exit 1
                fi
        	printf ".";
                sleep 1;
        done
	echo
    	myPid=`lsof -i:$appPort|grep LISTEN|awk '{print $2}'`
	echo "running: PID:$myPid"
}

function stop(){
   	echo "Stopping LinuxExporter..."
	myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
   	if [ "$myPid" != "" ]; then
                echo 0 > $isWhliePid
                kill $myPid
        fi
	printf "Waiting for LinuxExporter..."
        while true;
	do
  		myPid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
		if [ "$myPid" = "" ] ; then break; fi;
  		printf ".";
  		sleep 1;
	done
	echo
}

case "$1" in
   start)
    start
    status
   ;;
   stop)
    stop
    status
   ;;
   restart)
        $0 stop
        $0 start
   ;;
   status)
   	status
   ;;
   *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit $?
   ;;
esac
